# Generated by Django 4.0.2 on 2022-02-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email_Address',models.EmailField(max_length=20)),
                ('Text', models.CharField(max_length=20)),
            ],
        ),
    ]
